### ISSUE TITLE
Hello, how to quickly reproduce your analysis work?

### ISSUE THREAD

**Issue by Jiahe-Sun** [maehrlab/pharyngeal_endoderm_development#1]
Hello, I am very interested in your work, how can I reproduce your analysis through freezer, I checked the github introduction of freezer, but still don't know where to start, looking forward to your reply, thank you!

**Comment by ekernf01** [comment]
Hi @sunjiahe-hub ! I am not at the Maehr lab anymore, so whatever they say supersedes this, but I can try to make suggestions. The full output from `freezr` is not included in this repo, but `freezr` is only part of the solution anyway. It helps keep specific executions of evolving code together with the figures it produced and the environment it was run in, BUT, it is no help to recreate that environment. 

For recreating an R environment, my tool of choice would be `renv`. Unfortunately, `renv` did not exist when we started this project. Its predecessor (`packrat`) was very cumbersome, and created libraries that are too big to upload to github. If there is still a minimal packrat output such as a lockfile associated with the project, that might be enough to recreate the environment, but I don't have that lockfile.

If you are OK with the environment and the details of the results being slightly different, I would recommend installing R version ~3.4, freezr, Seurat version 2, and [`thymusatlastools2`](https://github.com/maehrlab/thymusatlastools2). (Rswitch is a great tool if you are on a Mac and need to install older R versions.) 

You can then start in [main.R](https://github.com/maehrlab/pharyngeal_endoderm_development/blob/main/scRNA_analysis/main.R). It may not be exactly the same as our figures but it will help you understand the order of the operations that we did. In particular, 

```
flash_freeze = configure_flash_freeze( project_directory = proj_dir, setup_scripts = "setup.Rmd" )
```

This sets up a function `flash_freeze` that will run `setup.Rmd` prior to each analysis script. This allows global access to functions and variables,, defined in `setup.Rmd`, that we reuse throughout the paper, such as a consistent set of colors for use in all figures. Otherwise, it's just basically wrapping `source`. So `flash_freeze( analyses_to_run = "atlas/assemble.Rmd" )` means approximately the same as `source("setup.R"); source("atlas/assemble.R")`, but it just takes care of some boring stuff like extracting `R` files from `Rmd` and sending the output to a directory structure that mirrors the scripts (`atlas` to `atlas`, `foxn1_ko` to `foxn1_ko`, etc).

**Comment by ekernf01** [comment]
I want to add that this is an extremely hard thing to do. Coming out of grad school in stats, I had no training to prepare me for the level of complexity of single-cell RNA software dependencies and iterative analysis. I tried diligently for 4 years and I am still learning how to get stuff to be reproducible. I expect the cell types we find would also be found by different analysis methods, but especially with labeling by hand of unsupervised clustering results, it may require a human in the loop.
